config/routes.rb
Estimate::Application.routes.draw do
  resources :items

  root :to => 'items#index'
end

app/models/estimation.rb
class Estimation
  include Mongoid::Document
  field :author, type: String
  field :effort, type: Integer

  embedded_in :item
end

app/models/item.rb
class Item
  include Mongoid::Document
  field :description, type: String
  
  embeds_many :estimations
  accepts_nested_attributes_for :estimations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def item_params
      params.require(:item).permit()
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  = f.text_field :description
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estimate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="estimator">
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>